services:
  app:
    build:
      args:
        ARG_LINUX_LOCALE: en_US.UTF-8
        ARG_USER_UID: ${ARG_USER_UID}
        ARG_USER_GID: ${ARG_USER_GID}
        ARG_PHP_VERSION: 8.3
      context: .
    depends_on:
      - mariadb
    working_dir: /home/user/dream_squad_test
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
    tty: true
    volumes:
      - app_local:/usr/local
      - ~/.ssh:/home/user/.ssh
      - ~/.gitconfig:/home/user/.gitconfig
      - ~/.bash_history:/home/user/.bash_history
      - .:/home/user/dream_squad_test
      - ./devops/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./devops/nginx/log:/var/log/nginx
      - ./site-exemplo:/var/www/html/site-exemplo
      - ./wordpress:/var/www/wordpress
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 40M
  mariadb:
    image: mariadb:11.6.2-ubi
    command: --default-authentication-plugin=mariadb_native_password
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: wordpress
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: on-failure:3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
volumes:
  app_local:
  mariadb_data:
