services:
  app:
    build:
      args:
        ARG_LINUX_LOCALE: en_US.UTF-8
        ARG_USER_UID: ${ARG_USER_UID}
        ARG_USER_GID: ${ARG_USER_GID}
        ARG_PHP_VERSION: 8.3
      context: .
    depends_on:
      - mysql
    working_dir: /home/user/dream_squad_test
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
    tty: true
    volumes:
      - app_local:/usr/local
      - ~/.ssh:/home/user/.ssh
      - ~/.gitconfig:/home/user/.gitconfig
      - ~/.bash_history:/home/user/.bash_history
      - .:/home/user/dream_squad_test
      - ./devops/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./site-exemplo:/var/www/html/site-exemplo
      - ./wordpress:/var/www/wordpress
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
volumes:
  app_local:
  mysql_data:
